### ISSUE TITLE
No longer have cellular signal 

### ISSUE THREAD

**Issue by Perryman** [commaai/openpilot#22234] opened 2021-09-14 23:49 UTC
**Describe the bug**

Cellular connection always has 0 bars

**How to reproduce or log data**

Attempt to connect while in range of cellular service and not on WiFi. Restarting does not change bars. 

**Device/Version information (please complete the following information):**
 - Device: Comma 3 Cross Country
 - Dongle ID: 0fa272552c614918
 - Route: n/a
 - Timestamp: n/a
 - Version: openpilot 0.8.8, Subaru-community c860e9bc3a, AGNOS 1.4
 - Car make/model: 2016 Subaru Outback 3.6R

**Additional context**

Cellular connection worked for approximately 1 week and stopped working. Restarting does not resolve the issue. Exact date of failure unknown.

**Comment by adeebshihadeh** [comment] 2021-09-14 23:57
Duplicate of https://github.com/commaai/openpilot/issues/22115. Cherry-pick 84d37141a8edb2281bc56fe6556c7164a2f692d2 or run release3 to fix.

**Closed by adeebshihadeh** 2021-09-14 23:57 UTC
Labels: bug
