### ISSUE TITLE
Error: Communication Issue Between Processes deviceState, managerState

### ISSUE THREAD

**Issue by wowLookAmazingUsername** [commaai/openpilot#32027] opened 2024-03-27 08:38 UTC
### Describe the bug

Communication issues between processes

**Describe the bug**
Running into this error that disables OP shortly after starting up: Communication Issue Between Processes deviceState, managerState

**Which car does this affect?**
Toyota RAV4 2021

**Provide a route where the issue occurs**
4baf26681af2f7bd/2024-03-26--07-53-12/0

**openpilot version**
0.9.6
![IMG_3318](https://github.com/commaai/openpilot/assets/147543115/88b95a6b-837f-476c-a1c0-4b5c94632357)

### Provide a route where the issue occurs

4baf26681af2f7bd/2024-03-26--07-53-12/0

### openpilot version

0.9.6

### Additional info

Been experiencing this across different versions of OP for the past maybe 6-8 months

**Comment by wowLookAmazingUsername** [comment] 2024-03-27 12:03
Did it again today:
4baf26681af2f7bd/2024-03-27--07-40-56/0

**Comment by adeebshihadeh** [comment] 2024-03-31 00:47
Duplicate of #32034

**Closed by adeebshihadeh** 2024-03-31 00:47 UTC
Labels: bug
