### ISSUE TITLE
2023 Hyundai Sonata | Experienced start-up screen during engagement

### ISSUE THREAD

**Issue by BBBmau** [commaai/openpilot#27567] opened 2023-03-12 20:29 UTC
### Describe the bug

at the time of `400` in cabana I experienced the boot screen when wanting to change lanes. It pretty much kept driving but I had to change lanes myself while it was in the boot screen stage. I tried looking in cabana to see if there are any weird appearances but also noticed that the logs don't update whatsoever once i put the vehicle into reverse and begin driving. I'm assuming that logs should be changing values throughout the route and not just when it's stationary right when you start the car.

### Provide a route where the issue occurs

10b8dcf2fb80bf56|2023-03-12--10-53-47--3

### openpilot version

0.9.1

**Comment by adeebshihadeh** [comment] 2023-03-12 21:19
This is a rare bug where the UI freezes due to a bug in one of the display drivers. Duplicate of #27328.

**Closed by adeebshihadeh** 2023-03-12 21:19 UTC
Labels: bug
