### ISSUE TITLE
very dificult to engage openpilot Honda Passport

### ISSUE THREAD

**Issue by gricha01** [commaai/openpilot#2377] opened 2020-10-21 00:00 UTC
**Describe the bug**
on every drive it is very difficult to engage openpillot. It takes multiple tries to get it to engage.

**How to reproduce or log data**
Just try to engage openpilot. you will be on a straight open road and no one around and it takes me a numerous tries to get it to engage.

**Expected behavior**
I expect that when i push the set button it will engage every time just as if i was using the stock Honda cruise control.

**Device/Version information **

    Device: comma two
    Dongle ID: d5450ec7974784ca
    Route: d5450ec7974784ca|2020-10-20--17-06-17
    Timestamp: 17:12:01 / 17:12:46 / 17:14:27 / 17:14:52 / 17:15:48 / 17:16:47 / 17:16:50 / 17:16:58 / 17:17:10 / 17:19:10 / 17:20:11 / 17:20:55 / 17:20:59 / 17:22:14
    Version: openpilot v0.7.9-release
    Car make/model: Honda Passport 2019

**Additional context**
I know i am new, only have it 7 days, But i have used a cruise control my whole life. it is very difficult to get it to engage and stay engaged. sometimes it will come on and stay engaged for 5 / 10 seconds then beeboop off. over and over. takes like 7 tries every time.

**Comment by pd0wm** [comment] 2020-10-21 13:10
Looks like the problem is related to https://github.com/commaai/openpilot/issues/2376, so I'm going to close this issue.

**Closed by pd0wm** 2020-10-21 13:10 UTC
Labels: bug
