### ISSUE TITLE
LKAS Faults

### ISSUE THREAD

**Issue by Friestadt** [commaai/openpilot#31890] opened 2024-03-16 02:01 UTC
### Describe the bug

After 1 hour and 11 minutes I get a LKAS fault on my Comma 3.  Last update is February 27 2024.  I have been on a long drive and the timing is very consistent.  At least 5 times yesterday and 9 times today.  Thank You.  I really rely on Comma for my drives.

### Provide a route where the issue occurs

8963b43b84a9fb1b

### openpilot version

0.9.6-release/release3/e5d2ce5/Feb27

**Comment by sshane** [comment] 2024-03-16 06:03
Likely a duplicate of https://github.com/commaai/openpilot/issues/31745

You can reach out to moderators in the Toyota channel to get help updating your S-DSU

**Closed** 2024-03-16 06:04 UTC
Labels: bug
