### ISSUE TITLE
OS Update Required - Fails

### ISSUE THREAD

**Issue by ns3284** [commaai/openpilot#29104] opened 2023-07-23 15:00 UTC
### Describe the bug

On master-ci, and device says OS update is required, but fails to update immediately after pressing install and tells me to reboot. Tried 2 different networks and consistently fails. 

### Provide a route where the issue occurs

NA

### openpilot version

0.9.4 latest

**Comment by ns3284** [comment] 2023-07-23 15:01
![PXL_20230723_150107749 MP](https://github.com/commaai/openpilot/assets/43015596/8bbdccb3-8b6c-4587-920f-790b46876c6e)
![PXL_20230723_150059174 MP](https://github.com/commaai/openpilot/assets/43015596/6e3d72d6-e982-492b-ad36-bcb3561c4e55)
![PXL_20230723_150033549 MP](https://github.com/commaai/openpilot/assets/43015596/02cede9e-9b82-472b-a1d0-7b88d5da04d2)

**Comment by ridgewayer25** [comment] 2023-07-23 15:09
Same issue, didn’t see this when I was opening report for same thing

**Comment by Verylukyguy** [comment] 2023-07-23 15:36
Same problem for me on master and nightly.

**Comment by adeebshihadeh** [comment] 2023-07-23 18:56
This was caused by adding an import to functools.cache in [gpio.py](https://github.com/commaai/openpilot/blob/12ed894362dd22513a21de6689a31511b791e37b/common/gpio.py#L1), which was new in Python 3.9. We extensively test the update, but that was added after the update was merged. I'm going to look into setting up a test for this. It's fixed by 5831f9e5a0d74a03a1b6ebc7b87f6d76d0fc38ae.

**Closed by adeebshihadeh** 2023-07-23 18:56 UTC
Labels: bug

**Comment by ns3284** [comment] 2023-07-23 21:29
Is there an easy way to get the latest update? Haven't had the opportunity to play around with it, so I might be stuck in this update loop. SSH still work at this point? Just connect and do a git pull?

**Comment by adeebshihadeh** [comment] 2023-07-23 21:31
Yes, SSH still works and a git pull will fix (though it'll be more of a fetch & reset since master-ci is force pushed. You can also do a system reset by tapping on the screen as soon as it's booting up.
