### ISSUE TITLE
run_bridge.py doesn't work because HONDA_CIVIC sets pcmCruise to True

### ISSUE THREAD

**Issue by shundroid** [commaai/openpilot#32025] opened 2024-03-27 05:15 UTC
### Describe the bug

Thanks for fixing #32010 . This issue fixed fingerprint from CIVIC to HONDA_CIVIC and now the run_bridge.py can be properly launched.
But, there is a still problem that openpilot cannot be engaged. Even when cruise_button is set to DECEL_SET (or RES_ACCEL), self-driving doesn't start.

To my inspection, this is because now HONDA_CIVIC sets pcmCruise to True but the bridge doesn't support this mode.

( `selfdrive/car/honda/interface.py` )
```python
    if candidate in HONDA_BOSCH:
      # ...
    else:
      # ...
      ret.pcmCruise = True
```

The older version (I'm not sure) of openpilot sets `ret.pcmCruise = not ret.enableGasInterceptor` here.

When I set `False` instead of `True` here, the bridge works properly.

I don't think it is a good way to change to `ret.pcmCruise = False` . Ideally, the bridge should support pcmCruise mode, I think.

### OS Version

Ubuntu 20.04

### openpilot version or commit

bbd08baacd4898f1f78cdd7e72709cae7fce73cc

**Comment by sshane** [comment] 2024-03-27 05:45
Duplicate of https://github.com/commaai/openpilot/issues/31919

**Closed by sshane** 2024-03-27 05:45 UTC
Labels: PC
