### ISSUE TITLE
2022 Chrysler Pacifica steering tune

### ISSUE THREAD

**Issue by HaraldSchafer** [commaai/openpilot#25895] opened 2022-09-26 14:48 UTC
### Describe the bug

Steering plots show some oscillation for this drive. It fingerprinted as a 2019 Pacifica, is that a different EPS? Requested rlogs.

### Which car does this affect?

2022 Chrysler Pacifica

### Provide a route where the issue occurs

e51816839229e7c6|2022-09-23--16-29-28

### openpilot version

0.8.16-release
![Screenshot from 2022-09-26 08-14-48](https://user-images.githubusercontent.com/6804392/192314823-894031fb-06b7-49fc-924c-5d30a3181e8c.png)

**Comment by adeebshihadeh** [comment] 2023-03-07 18:22
duplicate of #25270

**Closed by adeebshihadeh** 2023-03-07 18:22 UTC
Labels: bug, car
