### ISSUE TITLE
macOS openpilot build fails

### ISSUE THREAD

**Issue by ntegan1** [commaai/openpilot#26729] opened 2022-12-08 18:51 UTC
## Info
List of issues and build output the user ran into while attempting to compile on mac.

#### Old Cabana generate_dbc_json.py
fixed by updating  
![image](https://user-images.githubusercontent.com/3820605/206541469-9f73fd41-20af-4414-824f-afb3906eebbc.png)

#### New cabana issue
unresolved  
![image](https://user-images.githubusercontent.com/3820605/206541580-600543ee-07c0-4dba-b960-b04409dcefd2.png)

#### mac sensord common/gpio.h issue
sensord pr includes linux/gpio.h by default, breaking mac build.  
https://github.com/commaai/openpilot/pull/24525  
can not compile gpio.cc and not compile sensord on mac to bypass temporarily.  
![image](https://user-images.githubusercontent.com/3820605/206541721-9e7e4c89-3f47-4699-b83c-b7ea8b55be59.png)

#### Panda compilation issues
![image](https://user-images.githubusercontent.com/3820605/206541858-6dddd2d6-516c-44a4-93e6-f19b870099ec.png)

#### libcurl link time issue
![image](https://user-images.githubusercontent.com/3820605/206542163-de963906-5297-46de-83e1-4b011108a2bc.png)

### OS Version

2021 MBP

### Additional info

-- discord user
mattdurtybull#5049

**Comment by adeebshihadeh** [comment] 2022-12-08 19:06
duplicate of #25112

**Closed by adeebshihadeh** 2022-12-08 19:06 UTC
Labels: PC
