### ISSUE TITLE
Chrysler: "LKAS Faulted" on Comma, not car

### ISSUE THREAD

**Issue by ns3284** [commaai/openpilot#25065] opened 2022-07-07 18:37 UTC
### Describe the bug

Comma device instantly shows as LKAS Faulted and auto cancels when I attempt to enable ACC. Tried rebooting device, but no luck. Car does not show that LKAS is faulted.

### Which car does this affect?

2022 Chrysler Pacifica Hybrid 

### Provide a route where the issue occurs

4395faadf0a373f2|2022-07-07--14-27-05--2

### openpilot version

0.8.15 Nightly (7/7/2022)

### Additional info

master-ci branch, 881099ac3e commit.

**Comment by adeebshihadeh** [comment] 2022-07-07 20:22
I think #25068 should fix your issue. Let me know if that fixes and if you have any more issues. We cleaned up a bunch of stuff while testing on our Ram 1500, but the Chrysler/Jeep platform is a bit different than the Ram.

**Comment by ns3284** [comment] 2022-07-07 21:32
Just updated lastest on master-ci, and still has an issue. Will upload latest log shortly.

**Comment by ns3284** [comment] 2022-07-07 21:34
4395faadf0a373f2|2022-07-07--17-19-45--11

**Comment by adeebshihadeh** [comment] 2022-07-08 20:20
Have you had a chance to update and test?

**Comment by ns3284** [comment] 2022-07-08 20:55
4395faadf0a373f2|2022-07-08--16-04-27--31
4395faadf0a373f2|2022-07-08--16-04-27--32

Faulted for new reason now. Also just now it appeared to ignore my cancel
button press. Will upload later.

**Comment by ns3284** [comment] 2022-07-08 21:30
Pressing cancel didn't always work. Need to hold the button down to
Disengage ACC

**Comment by adeebshihadeh** [comment] 2022-07-12 00:41
Which route did you have ignored button presses? Is it persistent or only at certain times?

I'm also looking into the faults, but looks like it's working for the most part? I see a few long drives over the weekend with long stretches of engagement.

**Comment by ns3284** [comment] 2022-07-12 00:54
Let me upload. When the warning popped up at lower speeds to grab the
wheel, it seems it may have been spamming the CAN bus (speculation) as the
cancel button was not being recognized easily. I'll reply again after I
upload logs, but not sure which segment it was exactly.

**Comment by ns3284** [comment] 2022-07-12 00:57
Can't seem to find the log in connect. Only goes back to a single log on
7/8 and there was one earlier in the day that I know for certain this
happened.

**Comment by adeebshihadeh** [comment] 2022-07-12 02:12
I checked all your routes from the last week, and the last one with steering faults was `4395faadf0a373f2|2022-07-07--17-19-45`, where you didn't have the fix yet. Are you sure you saw faults after that?

**Comment by adeebshihadeh** [comment] 2022-07-12 03:38
I couldn't reproduce your button issue, but #25125 should fix it. Previously, the command was limited to 50Hz as a side effect of the LKAS command rate limit that was enforced on the whole car controller. When that rate limit was moved, it got sent at 100Hz. This will further limit it to 20Hz.

**Comment by adeebshihadeh** [comment] 2022-07-13 02:00
@ns3284 are you still having issues on the latest code?

**Comment by ns3284** [comment] 2022-07-13 02:06
Tried today. Cancel button was more responsive. Appears to be better now.

**Comment by adeebshihadeh** [comment] 2022-07-13 02:27
Alright, I'll close this since I also checked your recent routes and there are no faults since the last one you reported.

**Closed by adeebshihadeh** 2022-07-13 02:27 UTC
Labels: bug, car, chrysler
