### ISSUE TITLE
Warn when PCM car disengages unexpectedly

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#24721] opened 2022-06-03 00:16 UTC
In this route, the car hit a bump while braking and ABS kicked in, causing the SCC to disengage without warning and openpilot to follow as well. d466fc4afcd0a050|2022-06-02--18-57-27--8

**Comment by adeebshihadeh** [comment] 2022-06-12 19:38
Duplicate of #23601

**Closed by adeebshihadeh** 2022-06-12 19:38 UTC
Labels: enhancement, car
