### ISSUE TITLE
error  when run the model supercombo.onnx in onnx_runner.py

### ISSUE THREAD

**Issue by fatsheep2020** [commaai/openpilot#24536] opened 2022-05-14 13:21 UTC
### Describe the bug

run carla and OP container in PC , there is error report: [AssertionError]
![image](https://user-images.githubusercontent.com/60244699/168427105-ec38a8d3-4880-4184-8920-e6d01c1491f5.png)

How to reproduce:
sudo INSTALL=1 ./start_carla.sh
enter openpilot container, then run launch_openpilot.sh
there will be a error log as above pic show.

### OS Version

Ubuntu 20.04

### openpilot version or commit

v0.8.14

### Additional info

this error will lead to 'movelV2' not alive, and after some study, this error happen when run the model supercombo.onnx in onnx_runner.py, at same time, check the file, it exist:
![image](https://user-images.githubusercontent.com/60244699/168427581-fb4cd2af-332d-44ca-92cf-f18d2238532b.png)

**Comment by maykonpacheco** [comment] 2022-05-17 03:24
I have the same problem.

**Comment by maykonpacheco** [comment] 2022-05-17 03:41
![image](https://user-images.githubusercontent.com/38124066/168723945-10b6e00f-5ff7-4d52-9262-d1c0718f3db0.png)

**Comment by maykonpacheco** [comment] 2022-05-21 16:47
#24576

**Comment by fatsheep2020** [comment] 2022-05-22 04:35
not exactly same issue, what I meet is there is model (onnx) read error which happened in onnx_runner.py  @maykonpacheco

**Comment by fatsheep2020** [comment] 2022-05-22 04:36
and the HMI have issue #24232

**Comment by maykonpacheco** [comment] 2022-05-22 16:20
In addition to the enconded error, mine also has this error in the model @fatsheep2020

**Comment by gijskoning** [comment] 2022-05-29 13:40
Hey, these errors have different causes. The encoderd one is legit and will be fixed with https://github.com/commaai/openpilot/pull/24676. 
@fatsheep2020 I am not sure how to fix your issue. Did you do all the correct steps to install openpilot that are listed in the readme?

**Comment by maykonpacheco** [comment] 2022-05-31 23:39
I have the same problem.
![image](https://user-images.githubusercontent.com/38124066/171300863-21035a47-0b64-4293-a384-1313c93c5fc3.png)

**Comment by HaraldSchafer** [comment] 2022-06-03 00:40
I could not reproduce this @maykonpacheco You still have this on latest master?

**Closed** 2022-06-12 01:26 UTC
Labels: PC
