### ISSUE TITLE
OP "nightly" Anomaly when checking for updates after rebooting.

### ISSUE THREAD

**Issue by haram-KONA** [commaai/openpilot#29763] opened 2023-09-03 05:58 UTC
### Describe the bug

If i reboot after updating, the "Download" item in the "software" menu will change to "fail to check for update", 
![20230903_143752](https://github.com/commaai/openpilot/assets/88036668/b97a09e2-2d7a-4732-9c36-2ffe6778c49e)

and if i click "check" again in this state, "up to date, last checked now" will be displayed normally.
![20230903_144140](https://github.com/commaai/openpilot/assets/88036668/80a44ed8-b7a7-440c-8da8-35122eb6128a)

If  reboot again in this normal state, “fail to check for update” will occur again and this state will continue to repeat.

### Provide a route where the issue occurs

dongleID 1618132d68afc876

### openpilot version

0.9.15 nightly version

**Comment by sshane** [comment] 2023-09-11 21:55
Duplicate of https://github.com/commaai/openpilot/issues/29156

**Closed by sshane** 2023-09-11 21:55 UTC
Labels: bug
