### ISSUE TITLE
Lexus IS: erroneous user disengagements

### ISSUE THREAD

**Issue by johnlu6518** [commaai/openpilot#21519] opened 2021-07-08 06:14 UTC
**Describe the bug**

Did not step on the gas, but disengagement 2 times without warning.

**How to reproduce or log data**
Device: Comma 2
Dongle ID: ec30903bb15db3ad
Route: ec30903bb15db3ad|2021-07-05--22-31-41
Timestamp: Tue, 6 Jul @ 11:05:44 & Tue, 6 Jul @ 11:11:14
Veraion: OP 0.8.5
Car make/model: Lexus IS 2017 200T

![圖片 1](https://user-images.githubusercontent.com/63284226/124871537-bd8cc400-dff6-11eb-9f6f-f93e70a5000f.jpg)

**Comment by adeebshihadeh** [comment] 2021-07-08 06:17
The full logs for that route aren't uploaded. Can you enable the "Upload Raw" toggle and connect your device to wifi?

**Comment by johnlu6518** [comment] 2021-07-08 06:32
Okay, I'm not at home, so I will upload it later.

**Comment by johnlu6518** [comment] 2021-07-08 11:45
Device online and the data uploaded now! Thanks a lot.

**Comment by sshane** [comment] 2022-02-02 07:12
Looks like the car's PCM disabled on its own, which could be caused by an accidental cancel button press, traction control activating or more. Do you have any more recent cases of this?

**Comment by adeebshihadeh** [comment] 2022-02-02 07:38
@johnlu6518 looks like your last routes are from September. Do you still have your device? If not, I think we can close this.

**Comment by adeebshihadeh** [comment] 2022-02-04 20:06
Closing due to inactivity. Feel free to reopen if you still have the issue.

**Closed by adeebshihadeh** 2022-02-04 20:06 UTC
Labels: car bug
