### ISSUE TITLE
Speed problems 

### ISSUE THREAD

**Issue by Na112786** [commaai/openpilot#21822] opened 2021-08-01 14:06 UTC
**Describe the bug**
Please, this is the second time I sent you coz I was that nothing changed in speed limit?! , I need help to fix my speed limit, iam in the way to travel by car, but like this situation it's danger, the speed 69mph too slow. 
Describe problems :
Everything was great on speed limit 84mph with version 0.8.5 . 
When I updated to version 0.8.6, I found problem with speed limit became charged to 69mph. And this speed is slow, so please can you help me to back my original speed limit 84 mph, pls.

Milestone: 2000.
Thank you.

**Device/Version information (please complete the following information):

Device: [comma two]
Dongle ID: [1631748f51929063]
Route: [1631748f51929063|2021-07-28--20-15-01]
Timestamp: [Unknown]
Version: [release2 (0.8.6)]
Car make/model: [honda pilot 2019]

**Comment by vanillagorillaa** [comment] 2021-08-01 19:00
Closing as this is a duplicate of https://github.com/commaai/openpilot/issues/21803

**Closed by vanillagorillaa** 2021-08-01 19:00 UTC
Labels: bug
