### ISSUE TITLE
LKA error / sudden loss of lateral control and device hard rebooting

### ISSUE THREAD

**Issue by ketosnacks** [commaai/openpilot#20151] opened 2021-02-25 00:30 UTC
**Description**

Was driving and the the vehicle unexpectedly veered out of the lane during a highway curve (in the overtaking/left lane).

Speed was steady but the lateral control went out, followed by an 'LKA error', then followed by the Comma hanging and rebooting (at this point the car displayed a 'Cruise Control Malfunction' error). When I stopped, turned off the car and rebooted the device and it was fine afterwards.

**How to reproduce or log data**

Unable to reproduce immediately under same external conditions. Data was synced via explorer. There are before and after video segments with a few seconds showing all trace lines disappearing from the OP Comma display prior to veering out of lane.

**Expected behavior**

Maintaining lateral control (and ideally warning of a loss from the device; only the stock warning chimed).

**Device/Version information (please complete the following information):**
 - Device: Comma2
 - Dongle ID: 74fc73caf41697fa
 - Route: Wed, Feb 24 @ 06:49 to 10:12
 - Timestamp: Approximately at 10:11 (with post-device-reboot video in following segments)
 - Version: OpenPilot v0.8.1
 - Car make/model: 2021 Toyota Rav4

**Additional context**

My thoughts - it was a bit mucky (snow/slush mist); might have been the radar that threw a code (from being covered in dust). I wiped down the logo where the radar is housed and it didn't seem to happen again. Could also have been the (Toyota LKA) camera. Weather was fair with direct sun from driver's side. Prior to using OP, some highway drives would result in the Toyota throwing an error when the radar/camera would get obstructed by ice/dirt. Could be a possible link.

**Comment by pd0wm** [comment] 2021-02-25 11:22
Duplicate of https://github.com/commaai/openpilot/issues/19874. Feel free to post your issue as a comment there so we have all the data.

Also wanted to let you know we are actively working on this. We're looking at it from different angles. We will be increasing the CPU core voltage on devices that are factory tuned to run lower, and we're also looking into any issues caused by the modem driver locking things up.

**Closed by pd0wm** 2021-02-25 11:22 UTC
Labels: bug
