### ISSUE TITLE
Comma 2 crashes and becomes unresponsive with: echo -en "1" > /data/params/d/DisableUpdates 

### ISSUE THREAD

**Issue by J0eKickass** [commaai/openpilot#2396] opened 2020-10-24 01:03 UTC
**Describe the bug**
I can confirm after much troubleshooting that this causes the Comma 2 to crash and become unresponsive on vehicle power down
echo -en "1" > /data/params/d/DisableUpdates
I was told that is the way to prevent auto updates, but it does not work.
Comma 2 will shutdown and become unresponsive after the car ignition is turned off, resetting the comma 2 will allow it to sleep and wake upon next using the car, but it will crash again at vehicle power off and won't come back on unless it is reset.

**How to reproduce or log data**
SSH into the Comma 2 and enter the command: echo -en "1" > /data/params/d/DisableUpdates

**Expected behavior**
Comma 2 will wake up the next time the car is used and will not crash every time the car is turned off.

**Device/Version information (please complete the following information):**
 - Device: Comma 2
 - Dongle ID: 783f2ad3c4e2874b
 - Version: Stock OP version 0.7.9
 - Car make/model: Honda CR-V 2019

**Additional context**
If anyone knows how to actually keep the Comma 2 from auto updating please tell me! I hate having to use Dragonpilot
Thank you

**Comment by adeebshihadeh** [comment] 2020-10-26 21:34
I can't reproduce this on 0.7.9, and there was a big params refactor done in 0.7.10. Feel free to reopen the issue if you have steps to reliably reproduce this or this isn't resolved in 0.7.10, which will be in release shortly.

**Closed by adeebshihadeh** 2020-10-26 21:34 UTC
Labels: bug
