### ISSUE TITLE
test_processes.py should fail if a car make is not tested

### ISSUE THREAD

**Issue by rbiasini** [commaai/openpilot#1116] opened 2020-02-18 00:34 UTC
**Describe the bug**
realized VW port isn't tested by process replay regression test. Would be nice if the test would automatically fail if a car port is missing from the test.

**Comment by jpancotti** [comment] 2020-02-19 06:38
Duplicate of #978

**Comment by quillford** [comment] 2020-02-19 07:07
They’re different tests and this is a different coverage check. test_car_models should test every model supported. test_processes should test every brand supported.

**Closed** 2020-02-26 19:31 UTC
Labels: good first issue
