### ISSUE TITLE
Loading screen while driving

### ISSUE THREAD

**Issue by MJR1989** [commaai/openpilot#23318] opened 2021-12-27 05:47 UTC
### Describe the bug

Openpilot was driving and suddenly the screen turned upside down for a moment then the screen turned off and the comma loading screen popped up openpilot never stopped driving the car but the video recording also turned off and froze on the uploaded video pulled over unplugged the c2 and plugged it back in and it functioned as designed afterwards 
![67DB6210-D103-48F7-A191-72BA021BE5A7](https://user-images.githubusercontent.com/96713527/147438578-1af9588e-a968-422b-88dc-11f4a5d87b18.jpeg)

### What hardware does this issue affect?

comma two

### Provide a route where the issue occurs

606ed67f89d79ddf|2021-12-26--23-11-25--3

### openpilot version

0.8.12

**Comment by pd0wm** [comment] 2021-12-28 10:06
@adeebshihadeh Duplicate of https://github.com/commaai/openpilot/issues/21539?

**Comment by adeebshihadeh** [comment] 2022-01-01 01:01
Yes, it's likely a duplicate. @MJR1989 can you connect your device to wifi and make sure to upload all the logs for the route in connect.comma.ai?

**Comment by adeebshihadeh** [comment] 2022-01-13 23:26
Looks like the rlogs are gone by now. This is likely a duplicate of a known issue that we plan to address in the next release.

**Closed by adeebshihadeh** 2022-01-13 23:26 UTC
Labels: bug
