### ISSUE TITLE
Steering unavailable Ram 1500 DT Ltd

### ISSUE THREAD

**Issue by CraigRam** [commaai/openpilot#30287] opened 2023-10-19 02:05 UTC
### Describe the bug

I have just installed the comma 3X when the adaptive cruise control is turned on, I get an error message steering temporarily unavailable. I have restarted and reset the device and reinstalled the current version of open pilot. 0.9 .4 with no success. I have checked the compatibility for the vehicle and it is compatible, the Comma team have set up the same, comma 3X on a ram 1500 DT Ltd

### Provide a route where the issue occurs

https://useradmin.comma.ai/?onebox=56f7f07241e11132%7C2023-10-19--01-36-29

### openpilot version

0.9.4

### Additional info

I have tried these branches
https://installer.comma.ai/commaai/nightly
https://installer.comma.ai/commaai/master-ci

https://github.com/commaai/openpilot/tree/nightly
https://github.com/commaai/openpilot/tree/master-ci

And they don't work I am back to the same error can you please link the original ram fault branch 
that worked. 

Please try this branch: https://github.com/commaai/openpilot/tree/fix-ram-1500-fault

Or use this installer URL during setup: https://installer.comma.ai/commaai/fix-ram-1500-fault

Cheers

**Comment by sshane** [comment] 2023-10-19 04:11
duplicate of https://github.com/commaai/openpilot/issues/30266

**Closed by sshane** 2023-10-19 04:11 UTC
Labels: bug
