### ISSUE TITLE
Hard Crash under operation

### ISSUE THREAD

**Issue by 8a9phrywet978ui** [commaai/openpilot#19978] opened 2021-01-31 04:40 UTC
**Describe the bug**

Comma 2 froze and rebooted while activated. 

**How to reproduce or log data**

9d8c378664ae56f2|2021-01-30--09-42-22--3

**Expected behavior**

To not crash while under operation

**Device/Version information (please complete the following information):**
 - Device: C2
 - Dongle ID: 9d8c378664ae56f2
 - Route: 9d8c378664ae56f2|2021-01-30--09-42-22--3
 - Timestamp: At very end of segment, between 9:46am and 9:48am
 - Version: release2-staging
 - Car make/model: 2019 Corolla Hatchback.
**Additional context**

N/A

**Comment by pd0wm** [comment] 2021-02-01 14:41
Closing due to duplicate of https://github.com/commaai/openpilot/issues/19874

**Closed** 2021-02-01 14:41 UTC
Labels: bug
