### ISSUE TITLE
Spontaneous disengagement/reboot

### ISSUE THREAD

**Issue by schultp** [commaai/openpilot#19513] opened 2020-12-16 00:29 UTC
**Describe the bug**

Cruising on expressway and OP spontaneously disengaged and the comma2 rebooted

**How to reproduce or log data**

Single occurrence. No steps at this time to reproduce. 

**Expected behavior**

No spontaneous disengagement of OP

**Device/Version information (please complete the following information):**
 - Device: comma2
 - Dongle ID: 0a5c7571d1d1b4a8
 - Route: 0a5c7571d1d1b4a8|2020-12-14--17-15-38--14
 - Timestamp: At 17:29 - 17:30
 - Version: 0.8.0
 - Car make/model: 2017 Chevrolet Volt

**Additional context**
Running OBD harness.

**Comment by pd0wm** [comment] 2020-12-16 14:27
Thanks for the report. We'll investigate the logs!

My current theory is the cellular modem driver sometimes locks up and triggers the watchdog. This is something we're investigating, and doesn't have an easy fix. This should be a very rare event though, so if you see it again let us know.

**Comment by Jon8RFC** [comment] 2021-01-10 22:14
I have some random reboots to share, but I don't recall when they were.  I'm happy to manually look through all of my logs and narrow it down if you can tell me which search term(s) to look for.

Device: comma2
Dongle ID: 03690f0d837307af
Route: 
Timestamp: 
Version: 0.8.1
Car make/model: 2018 Hyundai Sonata Limited Ultimate

**Comment by Jon8RFC** [comment] 2021-01-17 02:44
@pd0wm

**Describe the bug**

Rebooted idiopathically.

**How to reproduce or log data**

No known way to reproduce.

bootlog after the reboot:
03690f0d837307af|2021-01-16--15-22-35--0

**Expected behavior**

No random reboot.

**Device/Version information (please complete the following information):**
 - Device: comma2
 - Dongle ID: 03690f0d837307af
 - Route: 03690f0d837307af|2021-01-16--15-09-09--12
 - Timestamp: at the end of this route segment
 - Version: 0.8.1
 - Car make/model: 2018 Hyundai Sonata Limited Ultimate

**Additional context**

My car beeped twice quickly, no more than 10 seconds before the reboot.  It sounded like the seatbelt warning beep.
The cruise button was probably toggled on, but OP was not engaged.

**Comment by Jon8RFC** [comment] 2021-01-19 06:18
Random reboot as it's sitting here on the desk, plugged into a reliable 5v power supply (not the computer).
My uploads aren't going for some reason, but the random reboot was at 2021-01-19 at 00:15am.

**Comment by adeebshihadeh** [comment] 2021-01-19 07:40
Yes, this is possibly a hardware issue. We'd be happy to swap it our you, and if it doesn't turn out to be your hardware, we can look into it more. Can you contact support@comma.ai?

**Comment by pd0wm** [comment] 2021-02-01 14:40
Closing this issue since it probably was hardware failure. Keeping https://github.com/commaai/openpilot/issues/19874 open for software issues.

**Comment by newjacky2419** [comment] 2021-02-07 13:55
**Describe the bug**
 freeze and rebooted randomly.

**How to reproduce or log data**

No known way to reproduce.

**Expected behavior**

No random reboot.

**Device/Version information (please complete the following information):**

Device: comma2
Dongle ID: fe30a344d9e657bd
Route: （I don’t know how can I found it)
Timestamp: （I don’t know how can I found it)
Version: 0.8.1 (Dragonpilot)
Car make/model: 2020 Toyota Prius Prime

**Additional context**
When my comma two freeze I took cellphone to record. 

https://youtu.be/yotG_RFBYwQ

As you can see this time comma two reboot many times(4 times). 10 minutes later. It freeze and reboot again.

https://youtu.be/uNi_f-DNSDY

This time just reboot one time.

Is my Comma Two hardware failure? Or it just the bug?

**Comment by pd0wm** [comment] 2021-02-08 12:13
If it happens a lot it's usually a hardware failure. But try running openpilot release instead of dragonpilot before drawing any conclusions.

**Comment by amano3001** [comment] 2021-02-17 01:53
Hi, I just had this happen to me on a fresh install of a brand new comma 2 device. 2017 Prius. It happened between 4pm and 5pm today.

**Comment by newjacky2419** [comment] 2021-02-17 13:36
> If it happens a lot it's usually a hardware failure. But try running openpilot release instead of dragonpilot before drawing any conclusions.

I reinstalled Openpilot. But this time is worse than before. Almost like #19874 issue. Today I drove on the freeway. My comma two freeze and rebooted while engaged. When comma two restart completely, I still saw my LTA failure warning on my dashboard.

**Comment by VirtuallyChris** [comment] 2021-02-17 20:12
@amano3001 and @newjacky2419 please email support@comma.ai so we can get these devices back and get working units to you.

**Comment by michaelhonan** [comment] 2021-02-18 01:15
Had this Yesterday. Route ID (crash should be at the very end, or start of next segment): 4d70bc5e608678be|2021-02-17--14-14-39--3

It was a 35C/95F day, and my comma two froze then rebooted. Exactly as described here.

**Comment by adeebshihadeh** [comment] 2021-04-14 00:34
Closing this and tracking software related reboots in #19874.

**Closed by adeebshihadeh** 2021-04-14 00:34 UTC
Labels: bug
