### ISSUE TITLE
OP 0.8.11 devel-staging cruiseMismatch 

### ISSUE THREAD

**Issue by ffhspa** [commaai/openpilot#22930] opened 2021-11-16 16:27 UTC
### Describe the bug

With new version OP 0.8.11 i often get cruiseMismatch . Never happened in previous release. 
I have a Honda Civic Bosch Diesel
I dont have a route bcs i deactivated Logs and Uploads

### What hardware does this issue affect?

comma two

### Provide a route where the issue occurs

N/A

### openpilot version

0.8.11

**Comment by adeebshihadeh** [comment] 2021-11-16 16:29
Duplicate of #22903

**Closed by adeebshihadeh** 2021-11-16 16:29 UTC
Labels: bug
