### ISSUE TITLE
C3 Screen Too Bright @ Night

### ISSUE THREAD

**Issue by jsegill** [commaai/openpilot#33041] opened 2024-07-22 21:55 UTC
### Describe the bug

Since installing 0.9.7 screen brightness at night on the C3 has been way too bright. Usually the night compensation for brightness works well, seems to have changed w/ 0.9.7. 

Route below is an example of a bad screen brightness at night. 

Whole route has the issue happening. 

### Provide a route where the issue occurs

4ecfcac756318cbf/00000035--99d3637ece

### openpilot version

0.9.7, release3

### Additional info

Fixing the brightness compensation is good but I would suggest adding an alternative brightness toggle. The user would be able to easily override screen brightness settings if they do not like stock brightness settings.

**Comment by CruiseBrantley** [comment] 2024-07-23 01:03
It's not an intermittent issue at all, for me at least. Pick any route at night with this dongle `149d6f706527cfe1`
Here's 1 example `149d6f706527cfe1/00000115--907e342143`
Essentially just stuck at 100% brightness it seems, I only notice it at night (*every* time) but possibly any route just not being noticeable during the day.

**Comment by jkbkster** [comment] 2024-07-29 18:48
Night driving only possible with manual brightness setting currently

**Comment by wired4sound** [comment] 2024-07-29 20:32
Commenting to say I am having this issue as well recently.

Blinding at night.   Manually turn down.  Then during day, can't see screen unless I shade it from the sun to turn it back up again because I cranked it down the night before.

**Comment by adeebshihadeh** [comment] 2024-08-20 20:26
Can you guys test `installer.comma.ai/commaai/fix-too-bright`?

**Comment by MarcoTheDingo** [comment] 2024-08-21 11:42
@adeebshihadeh looks like that helped! Not as dim as I personally keep my infotainment, but it was enough that it wasn't blinding. Route: 5130484aa8069bad/000000c9--4b7e4e53c6

**Comment by MarcoTheDingo** [comment] 2024-08-27 20:01
@adeebshihadeh are you looking for any other users to test, or any other routes to merge this?

**Comment by adeebshihadeh** [comment] 2024-08-27 21:32
So that isn't a mergable branch, it's just a test. Now that it's been tested, I'll come up with a mergable branch for you guys to test soon.

**Comment by jsegill** [comment] 2024-08-27 21:55
I can also test in a couple of days. Just really busy the last week...

**Comment by jsegill** [comment] 2024-09-12 01:11
Worked well on this route today `4ecfcac756318cbf/00000000--abb1191d75/0`

**Comment by MarcoTheDingo** [comment] 2024-09-12 16:04
The more I use this branch the more it seems like it's just darkening the input from the cameras and not the actual screen. If I open the sidebar or go into settings it's just as bright as not being on this branch.

Looking back at old footage from previous releases, the screen was a lot darker. Is there a way to reinvestigate this as an auto brightness issue instead of the gamma input on the cameras?

**Comment by adeebshihadeh** [comment] 2024-09-12 16:20
> Looking back at old footage from previous releases

What footage? You can't tell this from the device's logs, unless you mean recording a video of the device with your phone?

**Comment by MarcoTheDingo** [comment] 2024-09-12 16:28
Yes looking at old footage I recorded of the comma 3 and from my own memory, it was a lot dimmer.

**Comment by jsegill** [comment] 2024-09-14 10:54
Can confirm the UI is bright. Screen is still bright at night.

**Comment by wired4sound** [comment] 2024-09-14 11:51
Also confirming.  How does this go on so long? Lol, does it not get dark in San Diego?  It's unusable at night without cranking it way down.   Then you can't see it in the morning without covering it with your hand to make it dark enough to see the settings to turn it back up.

**Comment by jsegill** [comment] 2024-09-18 17:35
The screen is the brightest at midnight. This was at 2400-0100 w. `Screen-Too-Bright`. `4ecfcac756318cbf/00000016--7005cf51a2/0`

**Comment by MarcoTheDingo** [comment] 2024-10-07 03:39
Here's an example of auto brightness mostly working. Seems to work best when there's changes to the brightness. In this route we start in my garage, then go to a sunset drive into twilight. It starts to dim with the sunset correctly until I get on the highway in which it full brights for a mile or two, then starts to auto dim again correctly: 5130484aa8069bad/0000012a--3c9d04250a

**Comment by MarcoTheDingo** [comment] 2024-11-13 05:19
@adeebshihadeh confirmed this bug is fixed by #33984! Finally, my eyes are spared. 🎉

**Closed** 2024-11-13 05:43 UTC
Labels: bug
