### ISSUE TITLE
Ford Bronco Sport: treats kph as mph

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#31411] opened 2024-02-12 10:13 UTC
Set to metric units on the car, and 30 kph set speed shows as 30 mph on the 3X. When setting 3X to metric, then it displays 48 kph

**Comment by incognitojam** [comment] 2024-02-12 21:01
duplicate of https://github.com/commaai/openpilot/issues/29494

**Closed** 2024-02-12 21:07 UTC
Labels: bug
