### ISSUE TITLE
Comma drained the battery

### ISSUE THREAD

**Issue by Henry-E** [commaai/openpilot#23663] opened 2022-01-29 18:32 UTC
### Describe the bug

Had the comma 2 for 6 months and haven't had an issue but in the last two weeks the car's battery has been fully drained twice. 

device id: 6e93caa903fc3530

### What hardware does this issue affect?

comma two

### Which car does this affect?

Toyota Corolla Hybrid 2021

### Provide a route where the issue occurs

none appear to have uploaded

### openpilot version

0.8.12 (or whatever is the latest release)

### Additional info

I've started parking further away from my house. Is it possible that the comma is continually trying to connect to wifi to upload the drives but keeps failing and retrying until the battery is fully drained?

**Comment by zorrobyte** [comment] 2022-01-29 20:58
Linking this to be re-opened, it's a more common issue than realized:
https://github.com/commaai/openpilot/issues/2696#issuecomment-1023572542

**Comment by robbederks** [comment] 2022-01-31 10:29
Looked into this briefly, but it looks like there aren't any logs uploaded since the 22nd, and before that it looks like you didn't have a "decent" drive since the 17th. Hybrids have notoriously small 12V batteries, which also doesn't help in this case.

On which dates did these issues happen? Also, if possible, it would be nice if you could have the device connected to wifi for a while to make sure all the local logs have uploaded. From the data before that, it looks like the power saving measures in openpilot worked as intended, and the device always shut down when the battery appeared to be getting low. This basically shuts down the "phone", but leaves the panda running in low-power mode. In most cases, this should be fine for at least 2 weeks of standby time.

That said, we have been working recently on drastically improving the panda power consumption in low-power mode too (see for example https://github.com/commaai/panda/pull/832). With this, it looks like we can get about a 2-3x reduction in stand-by power consumption.

**Comment by Henry-E** [comment] 2022-02-05 18:59
The latest drives should have uploaded by now. Thanks for checking it out

**Comment by robbederks** [comment] 2022-02-07 11:30
Just looked again, but unfortunately there doesn't seem to be that many logs from the time of your complaint.
Regardless, it does look like your battery is getting quite weak though (low-ish open cell voltage at around 12.0V while the car is off, a healthy battery usually sits more around the 12.4V mark), so I would suggest to have it load tested and possibly replaced if needed.

![image](https://user-images.githubusercontent.com/894159/152779647-5159e756-627c-479e-82ac-b13afa826b1d.png)

I can't immediately see any obvious failure of the monitoring we have in the logs from the last 60 days, and the upcoming low-power mode for the panda would have also helped, so I'm closing this issue for now. Feel free to re-open when you suspect there is an unexpected drain in the future!

**Closed by robbederks** 2022-02-07 11:30 UTC
Labels: bug

**Comment by Henry-E** [comment] 2022-02-07 12:16
ok, thanks for looking into it. The battery will be replaced in a week or two. Will update if there are any future issues.
