### ISSUE TITLE
Openpilot Long Control Behaves Poorly on 2017-2018 RAV4

### ISSUE THREAD

**Issue by dresden196** [commaai/openpilot#30232] opened 2023-10-13 01:56 UTC
### Describe the bug

When running chill mode/OP long on a 2017 Toyota RAV4, with a SDSU, and Comma Pedal, OP long occasionally drops to lower gears at highway speeds when not needed to maintain acceleration, will also occasionally stay in lower gears despite matching set speed. I sometimes have to physically step on the gas for OP Long to shift up to a higher gear. Also OP Long will refuse to coast which results in lower MPG. Occasionally OP Long will exceed past specified set limit by about 7 mph (Maybe more), only then realizing this, then decrease to specified set limit. 

### Which car does this affect?

Toyota RAV4 2017-2018

### Provide a route where the issue occurs

383ba03aecff2efa|2023-10-08--22-32-36--0

### openpilot version

0.9.5

**Comment by ntegan1** [comment] 2023-10-13 22:14
https://github.com/commaai/openpilot/issues/28047

**Comment by sshane** [comment] 2024-03-20 00:45
Duplicate of https://github.com/commaai/openpilot/issues/28047

**Closed by sshane** 2024-03-20 00:45 UTC
Labels: bug, car
