### ISSUE TITLE
Steering unavailable Ram 1500 DT Ltd

### ISSUE THREAD

**Issue by CraigRam** [commaai/openpilot#30288] opened 2023-10-19 02:18 UTC
### Describe the bug

I have just installed the comma 3X when the adaptive cruise control is turned on, I get an error message steering temporarily unavailable. I have restarted and reset the device and reinstalled the current version of open pilot. 0.9 .4 with no success. I have checked the compatibility for the vehicle and it is compatible, the Comma team have set up the same, comma 3X on a ram 1500 DT Ltd

### Which car does this affect?

Ram 1500 DT Limited

### Provide a route where the issue occurs

https://useradmin.comma.ai/?onebox=56f7f07241e11132%7C2023-10-19--01-36-29

### openpilot version

0.9.4

### Additional info

Thanks for trying the branch! The EPS torque looks similar, so we're good to merge! You can check out master-ci or nightly (more stable) branches for now until the next release, replacing fix-ram-1500-fault above.

 I have tried these branches and they don’t work. I’m back to the same error again.

https://installer.comma.ai/commaai/nightly
https://installer.comma.ai/commaai/master-ci

https://github.com/commaai/openpilot/tree/nightly
https://github.com/commaai/openpilot/tree/master-ci

can you reset up the branch for the Ram 
Fault as this worked. 

Please try this branch: https://github.com/commaai/openpilot/tree/fix-ram-1500-fault

Or use this installer URL during setup: https://installer.comma.ai/commaai/fix-ram-1500-fault

**Comment by sshane** [comment] 2023-10-19 04:11
duplicate of https://github.com/commaai/openpilot/issues/30266

**Closed by sshane** 2023-10-19 04:11 UTC
Labels: bug, car
