### ISSUE TITLE
Going to device settings causes BaseUI to stop

### ISSUE THREAD

**Issue by xps-genesis** [commaai/openpilot#2660] opened 2020-11-30 23:20 UTC
**Describe the bug**

go to setting, device. The base ui stops. settings is not available anymore. off-road display is blank.

**How to reproduce or log data**

**Expected behavior**

**Device/Version information (please complete the following information):**
 - Device: [Comma two]
 - Dongle ID: [6fe86b4e410e4c37]
 - Route: [NA]
 - Timestamp: [NA]
 - Version: [master-ci - e4e102b]
 - Car make/model: [Hyundai Genesis 2016]

**Additional context**

![image](https://user-images.githubusercontent.com/65239463/100678537-670e2780-333b-11eb-99f5-0f2f05829e51.png)

![image](https://user-images.githubusercontent.com/65239463/100678726-c9ffbe80-333b-11eb-8712-fd1975c2a3fe.png)

![image](https://user-images.githubusercontent.com/65239463/100677273-ae46e900-3338-11eb-9109-f2d1b784fce2.png)

**Comment by adeebshihadeh** [comment] 2020-11-30 23:32
Is this with stock openpilot (including the APK)? If so, include the commit in your bug report.

**Comment by gugupilot** [comment] 2020-11-30 23:52
> 
> 
> Is this with stock openpilot (including the APK)? If so, include the commit in your bug report.

yes, just copied the master-ci. updated with details

**Comment by adeebshihadeh** [comment] 2020-12-01 00:36
I can't reproduce on latest master. All of your latest routes are from a fork. Feel free to reopen if you can reproduce reliably on master or master-ci, not a fork rebased on master.

**Comment by adeebshihadeh** [comment] 2020-12-08 21:58
This should be fixed as of 9803d3fcdc9ceef32ec56b79dbe7194b164393e6.

**Closed by adeebshihadeh** 2020-12-08 21:58 UTC
Labels: bug
