### ISSUE TITLE
Panda not recognized on Comma 2 after recent update

### ISSUE THREAD

**Issue by Verylukyguy** [commaai/openpilot#23754] opened 2022-02-12 18:35 UTC
### Describe the bug

A few people are having an issue with their Comma device not recognizing the Panda after a recent update.

I believe that the Comma 3s have been fixed by ssh-ing in and reflashing the Panda, but the Comma 2s are giving an errors message and will not reflash.

Apparently, the commit that caused this problem in the first place has been reverted by Comma.

### What hardware does this issue affect?

comma two

### Provide a route where the issue occurs

No routes show up in Connect after the update.

### openpilot version

v0.8.13 

### Additional info

Dongle ID:  e38a02cae1ef1e0c

**Comment by JasonJShuler** [comment] 2022-02-13 01:50
Just to add some more detail:
It seems Panda firmware build from Panda commits on Feb 9 are causing Pandas to be unable to enter DFU mode. It seems to work normally otherwise - the problem shows up when updating to a version of OP that references a newer panda commit.

When the command to enter bootstub is sent, the panda resets immediately into normal mode (reset is confirmed as the debug console connection is terminated)

**Comment by jyoung8607** [comment] 2022-02-13 21:34
Several GM people ran into this with C2s. I ran into it a couple times with my C3 as well. The user-facing problem was "NO PANDA" in the UI. Upon digging deeper. we found `pandad` tanking with an assert [here](https://github.com/commaai/panda/blob/f56ebf5b776b677bf12ec772b0223274dd798999/python/__init__.py#L300
). I don't know the triggering condition, but I ass-u-me it related to commaai/panda#852. Myself and the GM users were running pretty current master-derived branches.

We were eventually able to get the affected users back online.

I did a SSH help session with one of them, and initially couldn't get their Panda back. Main problem was essentially the one that halted `pandad`, I couldn't get Panda to go into the bootstub. And since getting to DFU requires a trip through the bootstub, even though it was running DEV firmware, I couldn't get it into DFU either. Panda would respond to the reset, but come back as normal 0xddcc instead of 0xddee.

I *think* the resolution was having them shut their cars off. It turns out the user I worked with had his engine running while we were working. I had him shut off the car on a hunch, and after that I was able to get it in DFU. I can't see anything that would stop us from flashing based on ignition state. I dimly recall there was some issue with certain CAN activity affecting flashing, but this was from years ago and I can't remember enough detail to track it down and see if it's still a problem.

**Comment by adeebshihadeh** [comment] 2022-02-14 21:17
This was caused by https://github.com/commaai/panda/pull/817 and fixed with https://github.com/commaai/panda/pull/852. I appreciate that forks want to stay up to date, but I think this is a good reminder to base branches intended for users on more stable releases.

**Closed by adeebshihadeh** 2022-02-14 21:17 UTC
Labels: bug

**Comment by Verylukyguy** [comment] 2022-02-14 21:22
Agreed.  I created the issue also with the hope that the information and data would be helpful for all.
