### ISSUE TITLE
FCA Warning on Kia Niro EV 2020 - On 0.9.0 Master

### ISSUE THREAD

**Issue by DerGue69** [commaai/openpilot#26594] opened 2022-11-24 17:26 UTC
### Describe the bug

Updated to most recent 0.9.0. on my Kia Niro EV 2020 - And instantly I get the yellow "Check FCA" warning.
Thought this has been already fixed in 0.8.6

![2022-11-24 18 06 22](https://user-images.githubusercontent.com/96002277/203839657-66bb4193-4b11-4c91-bc43-019791b5b2e6.jpg)

### Provide a route where the issue occurs

6111bd7df5043394|2022-11-24--18-03-45

### openpilot version

0.9.0

**Comment by sshane** [comment] 2022-11-25 00:53
Duplicate of https://github.com/commaai/openpilot/issues/25221

**Closed by sshane** 2022-11-25 00:53 UTC
Labels: bug
