### ISSUE TITLE
DM not functioning properly

### ISSUE THREAD

**Issue by hscalzi** [commaai/openpilot#2415] opened 2020-10-26 16:21 UTC
Under low light conditions such as dusk 4:30 to 6:00 PM and an overcast day, DM gave numerous touch wheel warnings on a C2 running 0710_ZSS on a 2017 Prius Prime. On a 500 mile trip, the DM gave so many warnings that OP stopped functioning. All the while this was happening the DM Icon never went out or blinked. I Replaced C2 with my OP3t EON using 079_zss to complete the trip. Returned home from the trip and tested C2 at night to see if 0710_zss was responding to the mounting position on the windshield. Best night drive I have ever had using the C2 at night. Not one DM 

Dongle ID 93baa9d2d37562

Route: https://my.comma.ai/useradmin/?onebox=93baa9d2d37562cf%7C2020-10-25--09-29-13

<!-- Steps to reproduce the behavior: Drive at dusk or on an overcast day

**Expected behavior: Not to report any touch steering wheel notices.

**Device/Version information (please complete the following information): 0710_zss

 - Device: [e.g. EON/EON Gold/comma two] Comma 2

 - Car make/model: [e.g. Toyota Prius 2016]: 2017 Prius Pr

**Comment by adeebshihadeh** [comment] 2020-10-26 21:03
Duplicate of #2417 (this came first, but other one has more info)

**Closed by adeebshihadeh** 2020-10-26 21:03 UTC
Labels: bug
