### ISSUE TITLE
Honda Radarless: log nonAdaptive with openpilot longitudinal

### ISSUE THREAD

**Issue by MarcoTheDingo** [commaai/openpilot#31849] opened 2024-03-13 01:51 UTC
### Describe the bug

~~After either #31763 or #31799 , and the March 12th master-ci build, my dashboard no longer works as expected.~~ The lead car (mini car) no longer shows along with the adjacent cars, which show on my trim. It used to show up to 2 in each adjacent lane, even when using alpha longitudinal control.
Also when setting ACC under 25mph, or when the current speed falls under 25mph, a message shows on screen "Cannot set cruise: speed too low". Openpilot never disengages, but these issues never occurred before today.

EDIT: Seems to be related to being in standard cruise mode.

### Provide a route where the issue occurs

5130484aa8069bad/00000010--c76b9d991a/2

### openpilot version

0.9.7 / master-ci / 224ee9f / Mar 12

**Comment by sshane** [comment] 2024-03-13 02:48
Can you revert this and try again? https://github.com/commaai/openpilot/pull/31799

Can you also get a stock route where you cycle from closest to max distance on the dash and mark the beginning and end of that section?

**Comment by MarcoTheDingo** [comment] 2024-03-13 02:55
Issue seemed to be when testing the distance button, accidentally set it to standard cruise mode, but the UI did not update. This made something think the car was in standard cruise mode, while openpilot was sending ACC commands.

If using Stock ACC, the UI icon updates back and forth when switching and car makes a long beep.
If using openpilot ACC, the UI icon doesn't update, nor does it make a beep. Only symptom is mini cars no longer show and shows "slow speed" error when under 25 mph.

op long, with car in "standard" cruise mode: 5130484aa8069bad/00000012--f2f58aca39/0
Stock long, starting in "standard" cruise mode, then switching to ACC. Also played with lead distance button: 5130484aa8069bad/00000013--e85305cd64/1
op long starting in ACC mode, then switching back and forth between "standard" and ACC modes with lead: 5130484aa8069bad/00000014--26d854a52d/1

**Comment by sshane** [comment] 2024-03-13 03:40
Ah, so you're saying some ECU besides the camera is in non-adaptive cruise mode, and therefore is not caused by the distance button PR recently merged?

**Comment by sshane** [comment] 2024-03-13 04:53
I checked the first two routes in your last message, and no other signal outside of ACC_HUD matched exactly. My guess is the ECU that accepts the acceleration command messages (PCM) also manages an internal state of whether it should be doing standard cruise control or not, and just doesn't publish this state back out over CAN (both camera and PCM must look at the buttons to sync their states).

This supports this theory, you can see the PCM is reporting "ACC" is active, but the camera is not sending anything. This hints the PCM keeps its own adaptive cruise state as well as does non-adaptive cruise internally:

![image](https://github.com/commaai/openpilot/assets/25857203/feb87772-f1f4-4a55-8368-50667f55713d)


Going to block enabling in this non-adaptive state like we do when we're using stock long.

**Closed** 2024-03-13 06:42 UTC
Labels: bug
