### ISSUE TITLE
Toyota RAV4 XLE hybrid 2024 error my vehicle is not recognized. #32179

### ISSUE THREAD

**Issue by yahaplus** [commaai/openpilot#32190] opened 2024-04-13 04:02 UTC
### Describe the bug

Good afternoon. I am writing for the second time after Shane Smiskol's (https://github.com/commaai/openpilot/issues/32179) 
![Изображение WhatsApp 2024-04-10 в 20 52 32_2671d19a](https://github.com/commaai/openpilot/assets/166684589/d53dbd64-0a5f-4087-bf06-8e6f993e9110)
![Изображение WhatsApp 2024-04-10 в 20 52 33_b577629b](https://github.com/commaai/openpilot/assets/166684589/59826da0-a871-412f-9b5d-df71f18838df)
![Изображение WhatsApp 2024-04-11 в 08 46 27_011da2fa](https://github.com/commaai/openpilot/assets/166684589/62ddee32-9bc7-4ec7-8669-9c1136f5a8f2)
![Изображение WhatsApp 2024-04-11 в 08 46 28_28460d73](https://github.com/commaai/openpilot/assets/166684589/2865f55b-5774-461e-8943-85be6a5b8f24)
![Изображение WhatsApp 2024-04-11 в 18 51 26_9ffef863](https://github.com/commaai/openpilot/assets/166684589/f0b0a368-53ca-4968-95b4-b33f0302ae87)
![Снимок экрана 2024-04-12 204621](https://github.com/commaai/openpilot/assets/166684589/db365bc0-8395-4705-90cd-2b010bade596)
reply as he recommended to write again to the support. The problem, according to him, is in some part of the equipment. Please follow the link and familiarize yourself with the detailed information on my problem. Thank you. Have a good day. 

### Which car does this affect?

Toyota RAV4 XLE hybrid 2024 (VIN: JTME6RFV6RD557044)

### Provide a route where the issue occurs

results: google_104000190100648345810

### openpilot version

0.9.6

### Additional info

This is where I took the picture Shane Smiskol's asked me to take. https://github.com/commaai/openpilot/issues/32179
![Изображение WhatsApp 2024-04-12 в 11 11 32_572e959e](https://github.com/commaai/openpilot/assets/166684589/217a2d47-4300-4121-ab15-5a6c6221fdf6)
![Изображение WhatsApp 2024-04-12 в 11 11 33_9524d66b](https://github.com/commaai/openpilot/assets/166684589/520354f7-3651-4077-90c9-dd2e56110c98)
![Изображение WhatsApp 2024-04-12 в 11 11 33_23996251](https://github.com/commaai/openpilot/assets/166684589/c4305160-4c05-4830-bba8-f1e1856f608d)
![Изображение WhatsApp 2024-04-12 в 11 11 34_a0c801e4](https://github.com/commaai/openpilot/assets/166684589/c7721bb7-73c4-481c-96fd-de294c6a9217)
![Изображение WhatsApp 2024-04-12 в 11 11 34_d46a7d43](https://github.com/commaai/openpilot/assets/166684589/aa2ba174-07ec-4756-8931-c06a40bf93e5)
![Изображение WhatsApp 2024-04-12 в 11 11 35_24040030](https://github.com/commaai/openpilot/assets/166684589/84a09a8a-523e-438c-959b-0a285f586ba5)
![Изображение WhatsApp 2024-04-12 в 11 11 35_e9523a38](https://github.com/commaai/openpilot/assets/166684589/1807209e-5cb4-42c0-8d65-d787a2ee760a)

**Comment by sshane** [comment] 2024-04-13 07:40
Duplicate of https://github.com/commaai/openpilot/issues/32179

**Closed by sshane** 2024-04-13 07:40 UTC
Labels: bug, car
