### ISSUE TITLE
Toyota: OP occasionally releases brakeHold when pressing resume button

### ISSUE THREAD

**Issue by jsegill** [commaai/openpilot#29255] opened 2023-08-05 23:40 UTC
### Describe the bug

If brakeHold is active and OP has already been activated prior. While at a stop w/ brakeHold active, OP occasionally releases the brakeHold when pressing the resume button. When at a stop w/ brakeHold active OP should either continue holding the brakeHold or resume OP selfdrive when the resume button is pressed. 

Release of brakeHold by OP while pressing resume may confuse the driver into thinking OP is active when it is not. This presents a particular issue in tight stop and go traffic. When the user expects to resume OP after some type of long issue forced them to disengage. Pressing resume at a small distance w/o OP activating but releasing the brakeHold could in theory cause an accident to an unfamiliar user. 

Stock Toyota ACC requires driver to press resume twice (initial + confirm) or press gas pedal (picture below) in order to enable stock ACC while brakeHold is active. 

![160724381-e597ebe5-d096-4a98-ba24-389c31e23ee1](https://github.com/commaai/openpilot/assets/75038839/72756d2a-234c-4440-b1f6-b5ac9f3dc726)

### Which car does this affect?

Toyota Corolla Hatchback 2019, many tss2 Toyotas

### Provide a route where the issue occurs

4ecfcac756318cbf|2023-08-05--18-43-56--2

### openpilot version

0.9.4

### Additional info

Allowing OP to resume in a brakeHold state like the stock Toyota ACC does would be matching industry standards. When brakeHold is active, the car is already in a state of selfdrive. Since no one is pressing the brake or controlling the car, other than the car.  

Issue started in 0.8.11 when brakeHold event was classified as a human pressing the brake.

**Comment by sshane** [comment] 2023-08-07 22:18
duplicate of https://github.com/commaai/openpilot/issues/23095

**Closed by sshane** 2023-08-07 22:18 UTC
Labels: bug, car
