### ISSUE TITLE
Communication Issue Between Processes: driverMonitoringState

### ISSUE THREAD

**Issue by goodchoom** [commaai/openpilot#29064] opened 2023-07-20 21:21 UTC
### Describe the bug

openpilot was unavailable during the first several minutes of my morning drive, and would not become available. The DMoji was missing as well. After restarting the car I was able to engage openpilot for the rest of my drive with no further issues.

### Provide a route where the issue occurs

5c49984c8efb9c9c|2023-07-20--06-54-51--0

### openpilot version

90153bb3d954364e941fdfbea21d117ff4bee13e

**Comment by adeebshihadeh** [comment] 2023-07-20 21:24
Duplicate of #28919

**Closed by adeebshihadeh** 2023-07-20 21:24 UTC
Labels: bug
